### ISSUE TITLE
Improve Error Page

### ISSUE THREAD

**Issue by HoodieRocks** [Datapack-Hub/frontend#16]

**Comment by Kefaku** [comment]
What kind of improvements are are do you have in mind?

**Comment by HoodieRocks** [comment]
Something more than the current one, its too plain and boring

**Comment by Kefaku** [comment]
> Something more than the current one, its too plain and boring

So purely graphical improvements and no functional changes?

**Comment by HoodieRocks** [comment]
Possibly links to go back to a previous page and/or common pages

**Comment by Kefaku** [comment]
I'll try to come up with something.
