### ISSUE TITLE
Fix E2E Tests

### ISSUE THREAD

**Issue by HoodieRocks** [Datapack-Hub/frontend#20]
**Is your feature request related to a problem? Please describe.**
The E2E tests are weird and have low coverage, we need someone to improve them and add a few more.

**Describe the solution you'd like**
Someone should help fix E2E tests and maybe add more tests, a PR is recommended

**Comment by Battledash-2** [comment]
What's E2E?

**Comment by HoodieRocks** [comment]
End to End testing
